app/APP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

app/account/urls.py
from django.urls import path
from .views import UserLoginView, UserRegisterView, UserLogoutView, UserProfileView, UserPasswordResetView, \
    UserPasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, UserFollowView, UserUnfollowView,\
    EditUserView


app_name = 'account'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>', UserProfileView.as_view(), name='profile'),
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id/', UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id/', UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user/', EditUserView.as_view(), name='edit_user'),

]

app/home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PoseCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.LikePostView.as_view(), name='like'),
]

app/templates/inc/messages.html
{% if messages %}
	{% for message in messages %}
		<p class="alert alert-{{message.tags}}">{{message}}</p>
	{% endfor %}
{% endif %}

app/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
        {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'account:profile' request.user.id %}">Profile</a>
            <a class="nav-link active" href="{% url 'account:logout' %}">Logout</a>
        {% else %}
            <a class="nav-link active" href="{% url 'account:register' %}">Register</a>
            <a class="nav-link active" href="{% url 'account:login' %}">Login</a>
        {% endif %}
    </div>
</nav>