app/APP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

app/account/urls.py
from django.urls import path
from .views import UserLoginView, UserRegisterView, UserLogoutView, UserProfileView, UserPasswordResetView, \
    UserPasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, UserFollowView, UserUnfollowView,\
    EditUserView


app_name = 'account'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>', UserProfileView.as_view(), name='profile'),
    path('reset/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id/', UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id/', UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user/', EditUserView.as_view(), name='edit_user'),

]

app/home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PoseCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.LikePostView.as_view(), name='like'),
]

app/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    # title = models.CharField(max_length=100, default=None)
    # title = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.user} - {self.slug} {self.updated}'

    def get_absolute_url(self):
        return reverse('home:post_detail', args=[self.id, self.slug])

    def like_count(self):
        return self.post_like.count()

    def user_can_like(self, user):
        user_like = user.user_like.filter(post=self)
        if user_like.exists():
            return True
        return False


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('Comment', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_like')

    def __str__(self):
        return f'{self.user} Like {self.post.slug}'

app/home/forms.py
from django import forms
from pyexpat import model

from .models import Post, Comment


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)


class CommentCreatedForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widget = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class PostSearchForm(forms.Form):
    search = forms.CharField()

app/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Post, Comment, Like
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostCreateUpdateForm, CommentCreatedForm, CommentReplyForm, PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.


class HomeView(View):
    form_class = PostSearchForm

    def get(self, request):
        posts = Post.objects.all()
        # posts = Post.objects.order_by('-created')
        if request.GET.get('search'):
            posts = Post.objects.filter(body__contains=request.GET['search'])
        return render(request, 'home/index.html', {'posts': posts, 'search_form': self.form_class})


class PostDetailView(View):
    form_class = CommentCreatedForm
    form_reply_class = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, post_id, post_slug):
        comments = self.post_instance.pcomments.filter(is_reply=False)
        disable_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            disable_like = True
        return render(request, 'home/details.html', {'post': self.post_instance, 'comments': comments,
                                                     'form': self.form_class, 'reply_form': self.form_reply_class,
                                                     'disable_like': disable_like})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'Your comment submit successfully', 'success')
            return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, 'deleted your post', 'success')
        else:
            messages.error(request, 'you cant deleted this post', 'danger')
        return redirect('home:home')


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not request.user.id == post.user.id:
            messages.error(request, 'you cant updated this post', 'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'home/update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()

            messages.success(request, 'you updated this post', 'success')
            return redirect('home:post_detail', post.id, post.slug)


class PoseCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, 'home/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, 'create new post', 'success')
            return redirect('home:post_detail', new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    def post(self, request, post_id, comment_id):
        form = CommentReplyForm(request.POST)
        post = get_object_or_404(Post, pk=post_id)
        comment = get_object_or_404(Comment, pk=comment_id)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'your reply submited successfully', 'success')
        return redirect('home:post_detail', post.id, post.slug)


class LikePostView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        like = Like.objects.filter(user=request.user, post=post)
        if like.exists():
            messages.error(request, 'you already liked this post', 'danger')
        else:
            Like.objects.create(post=post, user=request.user)
            messages.success(request, 'you like this post', 'success')
        return redirect('home:post_detail', post.id, post.slug)

app/home/templates/home/create.html
{% extends 'base.html' %}

{% block title %} Create {% endblock %}

{% block content %}
	<form action="" method="post" novalidate>
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Create">
	</form>
{% endblock %}

app/home/templates/home/details.html
{% extends 'base.html' %}

{% block title %} Details {% endblock %}

{% block content %}

	{% if request.user.username == post.user.username %}

		<a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete Post</a>
		<a href="{% url 'home:post_update' post.id %}" class="btn btn-info">Update Post</a><br>
	{% endif %}

	<a href="{% url 'account:profile' post.user.id %}">{{ post.user.username }} </a><br>
	<h2> {{ post.slug }} </h2>
	<p> {{ post.body }} </p>
	<small> updated: {{ post.updated |date:"Y - M - d" }} </small><br>
	<small> created: {{ post.created |date:"Y - M - d" }} </small><hr/>

	{% if request.user.is_authenticated %}
		<a href="{% url 'home:like' post.id %}" class="{% if disable_like %} disabled {% endif %} btn btn-primary col-md-2">Like {{ post.like_count }}</a></br>
		<form action="" method="post" novalidate>
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Send">
		</form><br>
	{% else %}
		<p class="alert alert-danger">Only logged in users can comment.</p>
	{% endif%}

	{% for comment in comments %}
		<div class="card bg-dark text-white">
			<p class="card-header">{{ comment.user }} | {{ comment.created | timesince }}</p>
			<p class="card-body">{{ comment.body }}</p>

			{% if request.user.is_authenticated %}
				<form action="{% url 'home:add_reply' post.id comment.id %}" method="post" novalidate>
					{% csrf_token %}
					{{ form.as_p }}
					<input type="submit" value="Reply">
				</form>
			{% endif%}

			{% with replies=comment.rcomments.all %}
				{% for reply in replies %}
					<p class="bg-primary p-3 m-2"> {{ reply.user }} <br/> {{ reply.body }} </p>
				{% endfor %}
			{% endwith %}
		</div><br>
	{% empty %}
		<p>No comments yet!</p>
	{% endfor %}

{% endblock %}

app/home/templates/home/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

    <form action="" method="get">
        {{ search_form.as_p }}
        <input type="submit" value="Search">
    </form><br><br>

    <div class="card">
        {% if request.user.is_authenticated %}
            {% for post in posts %}
                <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.slug }}</a>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

app/home/templates/home/update.html
{% extends 'base.html' %}

{% block title %} Update {% endblock %}

{% block content %}
	<form action="" method="post" novalidate>
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Update">
	</form>
{% endblock %}